# Generated by Django 3.2 on 2021-04-27 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=50)),
                ('brand', models.CharField(blank=True, help_text='Product brand', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Product description', max_length=200, null=True)),
                ('unit', models.CharField(choices=[('u', 'Unit'), ('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Litre'), ('ml', 'Millilitre')], help_text='Product unit', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('quantity', models.IntegerField(help_text='Quantity available')),
                ('enabled', models.BooleanField(help_text='This product is for sell or not')),
                ('category', models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.category')),
            ],
            options={
                'ordering': ['name', 'brand'],
            },
        ),
    ]
