# Generated by Django 3.2 on 2021-04-27 13:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity sold')),
                ('bill_id', models.UUIDField(default=None, help_text='Associated bill id', null=True)),
                ('product', models.ForeignKey(help_text='Sold product', on_delete=django.db.models.deletion.RESTRICT, to='stock.product')),
            ],
            options={
                'ordering': ['bill_id', 'product'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, help_text='Date of purchase')),
                ('time', models.TimeField(auto_now_add=True, help_text='Time of purchase')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('items', models.ManyToManyField(help_text='Purchased items', to='stock.ProductSale')),
            ],
            options={
                'ordering': ['date', 'time', 'total'],
            },
        ),
    ]
