# Generated by Django 3.2 on 2021-04-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_bill_productsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='enabled',
            field=models.BooleanField(default=True, help_text='This product is for sell or not'),
        ),
    ]
