# Generated by Django 3.2 on 2021-04-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_product_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Product description', max_length=400, null=True),
        ),
    ]
