# Generated by Django 3.2 on 2021-04-27 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20210427_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='items',
        ),
        migrations.RemoveField(
            model_name='productsale',
            name='bill_id',
        ),
        migrations.AddField(
            model_name='productsale',
            name='bill',
            field=models.ForeignKey(default=None, help_text='Associated bill', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.bill'),
        ),
    ]
