# Generated by Django 3.2 on 2021-04-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20210427_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsale',
            options={'ordering': ['bill', 'product']},
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(help_text='Product brand', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Product enabled'),
        ),
    ]
