# Generated by Django 3.2 on 2021-04-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20210428_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Final product price', max_digits=10),
        ),
    ]
