# Generated by Django 3.2 on 2021-04-30 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_productsale_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['date', 'time']},
        ),
        migrations.RemoveField(
            model_name='bill',
            name='total',
        ),
    ]
