# Generated by Django 3.2 on 2021-04-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20210430_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='summary',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
