# Generated by Django 3.2 on 2021-05-11 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_auto_20210430_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Base cost per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Quantity available'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Checkout cost per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Checkout price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity sold'),
        ),
    ]
