# Generated by Django 3.2 on 2021-04-27 11:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, help_text='Date of purchase')),
                ('time', models.TimeField(auto_now_add=True, help_text='Time of purchase')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['date', 'time', 'total'],
            },
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity sold')),
                ('billing', models.ForeignKey(help_text='Associated bill', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.bill')),
                ('product', models.ForeignKey(help_text='Sold product', on_delete=django.db.models.deletion.RESTRICT, to='stock.product')),
            ],
            options={
                'ordering': ['billing', 'product'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='items',
            field=models.ManyToManyField(help_text='Purchased items', to='shop.ProductSale'),
        ),
    ]
