# Generated by Django 3.2.6 on 2021-11-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='fullname',
            field=models.CharField(default='', help_text='Full name of employee', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Salary of employee', max_digits=10),
        ),
    ]
