# Generated by Django 3.2.6 on 2021-12-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_staff_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='birth',
            new_name='born',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='fullname',
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.TextField(help_text='Address of employee', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Salary of employee', max_digits=15),
        ),
    ]
