# Generated by Django 3.2.6 on 2021-12-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20211201_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='admin',
            field=models.BooleanField(default=False, help_text='True for admin, false otherwise'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.TextField(help_text='Full address', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='born',
            field=models.DateField(help_text='Birth date'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly salary', max_digits=15),
        ),
    ]
